def fractional_knapsack(weights, values, capacity):

    items = []

    for i in range(len(weights)):
        ratio = values[i] / weights[i]

        items.append(
            (ratio, weights[i], values[i])
        )

    # Sort by value/weight ratio
    items.sort(reverse=True)

    total_value = 0

    for ratio, weight, value in items:

        if capacity >= weight:

            capacity -= weight
            total_value += value

        else:

            fraction = capacity / weight
            total_value += value * fraction
            capacity = 0
            break

    return total_value


weights = [10, 20, 30]
values = [60, 100, 120]
capacity = 50

result = fractional_knapsack(
    weights,
    values,
    capacity
)

print("Maximum Value:", result)